name: Verification
on:
  push:

env:
  NODE_VERSION: "18.x"
  DOCKER_BUILDKIT: 1

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: ls
        run: ls -la

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: setup
        run: npm run setup:ci --if-present
      - name: npm install
        run: npm ci
      - name: node_modules
        run: ls -la ./node_modules
      - name: npm audit
        run: npm audit
        continue-on-error: true # XXX?

      - name: lint
        run: npm run lint
      - name: npm test:ci
        run: npm run test:ci --ignore-scripts

      - name: ng build
        run: |
          npm run dist
          ls -la dist
      - name: dist.zip
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  builds:
    if: github.ref == 'refs/heads/main'
    needs: build
    strategy:
      max-parallel: 6
      matrix:
        node: ["18.x", "20.x"]
        os:
          - ubuntu-latest
          - macOS-latest
          # - windows-latest # TODO? too slow
    runs-on: ${{ matrix.os }}
    name: Build @ node:${{ matrix.node }}@${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: setup
        run: npm run setup:ci --if-present
      - name: npm install
        run: npm ci

      - name: npm test:ci
        run: npm run test:ci --ignore-scripts

      - name: ng build
        run: npm run dist

  Dockerfile:
    # if: github.ref == 'refs/heads/main' # TODO? or XXX?
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        target:
          - base # XXX? overkill?
          - project # XXX? overkill?
          - test
          - dist
          - http-server
    name: "Dockerfile target:${{ matrix.target }}"
    steps:
      - uses: docker/build-push-action@v4
        name: docker build
        with:
          push: false
          target: ${{ matrix.target }}

  docker-compose:
    # if: github.ref == 'refs/heads/main' # TODO? or XXX?
    needs: Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        name: "docker compose up"
        with:
          up-flags: "--build --remove-orphans"

  codeQL:
    # if: github.ref == 'refs/heads/main' # TODO? or XXX?
    needs: build
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ["javascript"] #, "typescript"] # Redundant

    name: "CodeQL: ${{ matrix.language }}"
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
      - name: dist.zip
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: CodeQL
        uses: github/codeql-action/analyze@v2
